### PR TITLE
Implement Imgur Searching

### PR DESCRIPTION
**Pull request by preichelt**
- [ ] If quotations exist, use "Exact" search
- [x] Otherwise use "All of" search
- [ ] If "All of" search fails use "Any of" search.

### CODE REVIEW

**Comment by preichelt** [comment]
Just implementing "All of" search on this first go. Once we've tested that on the server I'll add the other searches.

**Comment by Kmcelyea** [comment]
Looks good to me

**Comment by rboylesDev** [comment]
Looks good to me too

**Comment by preichelt** [comment]
Thanks for the reviews dudes. Merging :rocket:

**Comment by preichelt** [comment]
Closes #5

**Pull request merged**
